// <auto-generated />
namespace CMP.Operation.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Employ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employ));
        
        string IMigrationMetadata.Id
        {
            get { return "201702010733178_Employ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
